GET http://localhost:3456

###
POST http://localhost:3456/api/auth/register
Content-Type: application/json

{
  "username": "Tony Bui 11111",
  "password": "Zxcasdqwe12"
}


###
POST http://localhost:3456/api/auth/login
Content-Type: application/json

{
  "username": "Tony Bui 11111",
  "password": "Zxcasdqwe12"
}